version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.10  # Use Python 3.10 Docker image for the executor
    working_directory: ~/repo  # Working directory for project
    environment:
      PYTHONUNBUFFERED: "1"  # Output is not buffered
      PIP_CACHE_DIR: /tmp/pip-cache  # Cache directory for pip to speed up builds

jobs:
  install_dependencies:
    executor: python-executor
    steps:
      - run:
          name: Clone repository
          command: |
            git clone https://github.com/adrian-krysiak/SimpleCalculatorApp.git .  # Clone your repo into the current directory
      - run:
          name: Install dependencies
          command: |
            python -m venv .venv  # Create a virtual environment
            . .venv/bin/activate  # Activate the virtual environment
            pip install --upgrade pip  # Upgrade pip to the latest version
            pip install -r requirements.txt  # Install dependencies

  run_tests:
    executor: python-executor
    steps:
      - checkout  # Checkout code (using CircleCI's default checkout)
      - run:
          name: Install dependencies
          command: |
            python -m venv .venv
            . .venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run unit tests
          command: |
            . .venv/bin/activate
            python -m unittest discover tests
      - store_artifacts:
          path: app.log
          destination: log
      - store_artifacts:
          path: results.json
          destination: results

  lint_code:
    executor: python-executor
    steps:
      - checkout  # Checkout code (using CircleCI's default checkout)
      - run:
          name: Install flake8
          command: |
            python -m venv .venv
            . .venv/bin/activate
            pip install flake8
      - run:
          name: Run lint checks
          command: |
            . .venv/bin/activate
            flake8 .

  build_docker_image:
    executor: python-executor  # Use the python-executor defined above
    steps:
      - checkout  # Checkout code (using CircleCI's default checkout)
      - setup_remote_docker:
          docker_layer_caching: true  # Enable Docker layer caching for faster builds
      - run:
          name: Build Docker image
          command: |
            docker build -t calculator-app .

  deploy:
    executor: python-executor
    steps:
      - checkout  # Checkout code (using CircleCI's default checkout)
      - run:
          name: Deploy application
          command: |
            echo "Deploying application..."

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_dependencies
      - lint_code:
          requires:
            - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
      - build_docker_image:
          requires:
            - install_dependencies
      - deploy:
          requires:
            - build_docker_image
